### ISSUE TITLE
looking for default constructor of an enum

### ISSUE THREAD

**Issue by clixtec** [axelspringer/polymorphia#5]
I've got an exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: Please provide a default constructor for class co.skyhawk.MyEnumType!
	at de.bild.codec.AbstractTypeCodec.getDefaultConstructor(AbstractTypeCodec.java:53)
	at de.bild.codec.AbstractTypeCodec.<init>(AbstractTypeCodec.java:25)
	at de.bild.codec.BasicReflectionCodec.<init>(BasicReflectionCodec.java:34)
	at de.bild.codec.PojoContext.resolve(PojoContext.java:93)
	at de.bild.codec.PolymorphicReflectionCodec.<init>(PolymorphicReflectionCodec.java:45)
	at de.bild.codec.PojoContext.calculateCodec(PojoContext.java:156)
	at de.bild.codec.PojoContext.getCodec(PojoContext.java:66)
	at de.bild.codec.PojoContext$AnyTypeCodecRegistry.getCodec(PojoContext.java:212)
	at de.bild.codec.MappedField.<init>(MappedField.java:76)
	at de.bild.codec.BasicReflectionCodec.<init>(BasicReflectionCodec.java:39)
	at de.bild.codec.PojoContext.resolve(PojoContext.java:93)
	at de.bild.codec.PojoContext.calculateCodec(PojoContext.java:160)
	at de.bild.codec.PojoContext.getCodec(PojoContext.java:66)
	at de.bild.codec.PojoContext$AnyTypeCodecRegistry.getCodec(PojoContext.java:212)
	at de.bild.codec.MapTypeCodec.<init>(MapTypeCodec.java:20)
	at de.bild.codec.SimpleMapTypeCodec.<init>(SimpleMapTypeCodec.java:19)
	at de.bild.codec.MapTypeCodec.getCodecIfApplicable(MapTypeCodec.java:50)
	at de.bild.codec.PojoContext.calculateCodec(PojoContext.java:141)
	at de.bild.codec.PojoContext.getCodec(PojoContext.java:66)
	at de.bild.codec.PojoContext$AnyTypeCodecRegistry.getCodec(PojoContext.java:212)
	at de.bild.codec.MappedField.<init>(MappedField.java:76)
	at de.bild.codec.BasicReflectionCodec.<init>(BasicReflectionCodec.java:39)
	at de.bild.codec.PojoContext.resolve(PojoContext.java:93)
	at de.bild.codec.PolymorphicReflectionCodec.<init>(PolymorphicReflectionCodec.java:45)
	at de.bild.codec.PojoContext.calculateCodec(PojoContext.java:156)
	at de.bild.codec.PojoContext.getCodec(PojoContext.java:66)
	at de.bild.codec.PojoContext$AnyTypeCodecRegistry.getCodec(PojoContext.java:212)
	at de.bild.codec.MappedField.<init>(MappedField.java:76)
	at de.bild.codec.BasicReflectionCodec.<init>(BasicReflectionCodec.java:39)
	at de.bild.codec.PojoContext.resolve(PojoContext.java:93)
	at de.bild.codec.PolymorphicReflectionCodec.<init>(PolymorphicReflectionCodec.java:45)
	at de.bild.codec.PojoContext.calculateCodec(PojoContext.java:156)
	at de.bild.codec.PojoContext.getCodec(PojoContext.java:66)
	at de.bild.codec.PojoContext.get(PojoContext.java:44)
	at de.bild.codec.PojoCodecProvider.get(PojoCodecProvider.java:43)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:43)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:55)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:37)
	at com.mongodb.FindIterableImpl.createQueryOperation(FindIterableImpl.java:228)
	at com.mongodb.FindIterableImpl.execute(FindIterableImpl.java:224)
	at com.mongodb.FindIterableImpl.into(FindIterableImpl.java:220)
...
Caused by: java.lang.NoSuchMethodException: co.skyhawk.MyEnumType.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at de.bild.codec.AbstractTypeCodec.getDefaultConstructor(AbstractTypeCodec.java:46)
	... 46 more
```

The exact MyEnumType changes, but it is always a special enum as described below.

I haven't been able to create a test case that reproduces this issue yet, but I have a suspicion that Polymorphia is being fooled by my interface/enum structure:

```
public interface Displayable {
    String getLocalizationTag();
}

public enum MyEnumType implements SomeInterface {
    enum members;
    public String getLocalizationTag() {
        return some function of name();
    }
}
```

It seems `PojoContext.calculateCodec()` doesn't pick up that it is an enum, and falls down to trying the PolymorphicReflectionCodec on it.

**Comment by webermich** [comment]
Hi Sean,

interesting finding.
We did not think of such a use case till today.
I created a test case for your issue and will try fixing it shortly.

https://github.com/axelspringer/polymorphia/blob/master/src/test/java/de/bild/codec/enums/TestEnums.java

Thanks for reporting it.

Michael

**Comment by webermich** [comment]
Hi Sean,

just release version 1.6.2 of Polymorphia containing a fix (hopefully) for your scenario.
Please check the test and let me know if I understood your use case.

https://github.com/axelspringer/polymorphia/blob/master/src/test/java/de/bild/codec/enums/TestEnums.java

Cheers Michael

**Comment by clixtec** [comment]
Works great thanks!
