### ISSUE TITLE
WildcardTypes

### ISSUE THREAD

**Issue by jklee14** [axelspringer/polymorphia#9]
Is It possible for you to code WildcardTypes?
It's very critical to what I'm doing and very much appreciated if you can support it!

public class GenericsExample {

	int test = 10;
	public List<? extends Fruit>basket;

}

15918 [main] ERROR de.bild.codec.PojoContext - WildcardTypes are not yet supported. ? extends com.volante.mainPackage.listGenTest.Fruit
org.apache.commons.lang3.NotImplementedException: WildcardTypes are not yet supported. ? extends com.volante.mainPackage.listGenTest.Fruit
	at de.bild.codec.PojoContext$1.get(PojoContext.java:58)
	at de.bild.codec.PojoContext.calculateCodec(PojoContext.java:268)
	at de.bild.codec.PojoContext.getCodec(PojoContext.java:141)
	at de.bild.codec.PojoContext$AnyTypeCodecRegistry.getCodec(PojoContext.java:106)
	at de.bild.codec.CollectionTypeCodec.<init>(CollectionTypeCodec.java:33)
	at de.bild.codec.ListTypeCodec.<init>(ListTypeCodec.java:17)
	at de.bild.codec.PojoContext.calculateCodec(PojoContext.java:280)
	at de.bild.codec.PojoContext.getCodec(PojoContext.java:141)
	at de.bild.codec.PojoContext$AnyTypeCodecRegistry.getCodec(PojoContext.java:106)
	at de.bild.codec.MappedField.<init>(MappedField.java:91)
	at de.bild.codec.BasicReflectionCodec.<init>(BasicReflectionCodec.java:45)
	at de.bild.codec.PojoContext.resolve(PojoContext.java:194)
	at de.bild.codec.PojoContext.calculateCodec(PojoContext.java:337)
	at de.bild.codec.PojoContext.getCodec(PojoContext.java:141)
	at de.bild.codec.PojoContext.get(PojoContext.java:119)
	at de.bild.codec.PojoCodecProvider.get(PojoCodecProvider.java:56)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:43)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:55)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:37)
	at com.mongodb.MongoCollectionImpl.getCodec(MongoCollectionImpl.java:1066)
	at com.mongodb.MongoCollectionImpl.executeInsertMany(MongoCollectionImpl.java:546)
	at com.mongodb.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:524)
	at com.mongodb.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:519)
	at com.volante.mainPackage.MongoTestList.insertMongo(MongoTestList.java:91)
	at com.volante.mainPackage.MongoTestList.main(MongoTestList.java:135)

**Comment by webermich** [comment]
Hi @jklee14 ,
I am not sure if it is possible to find solutions for all possible wildcard types (including <? super Class> and <? extends Class> or even an unbounded wildcard <?>). It might be possible to support some wildcard types and I actually tried to support wildcard types in an earlier version of polymorphia, but I failed to really implement a robust behaviour.

From my understanding wildcard types are especially helpful in method declarations as method arguments (but not in return typews or field declarations). Just look up PECS (producer extends consumer super)

Consider using a non-wildcard List like the following:
List<Fruit> fruitList = new ArrayList<Fruit>(); 
It is pretty clear what this list contains, anything that can be a Fruit or that extends Fruit.

Its hard to tell what the following list would contain. The compiler most likely won't allow you to add a Fruit to that list, evben though your declaration implies (somehow) its a List<Fruit>. Biut it could be any other list as well.
List<?> aListOfAnything = new ArrayList<Fruit>(); 

Even if you had a list as follows:
List<? extends Fruit> aSpecialicedListOfSomethingExtendingFruit = new ArrayList<AdvancedFruit>();

You would not be allowed (the compiler failes) to add a Fruit to aSpecialicedListOfSomethingExtendingFruit. Why? Because this could be a List<AdvancedFruit>();
The compiler will not know, what specialized list will be assigned to your field, hence adding things to your list will be challanging.

I really can't think of any use case where you want to declare bounded wildcard type fields in your pojo.

Please let me know, why this is so important for your use case.

Lastly: The only solution to support upper bound wildcard types like <? extends Fruit> is to ignore the existence of the wildcard type since at scanning time of the pojo I will only have the information that the list may contain something extending Fruit. I will not know, if all items in the list are at least of type AdvancedFruit (or any other subtype of Fruit).
Support for lower bound wildcards is from my point of view useless.

**Comment by webermich** [comment]
Hi @jklee14 ,
as you are not getting back on this, I assume you sorted the issue.
Hence, I will close this ticket.
Thanks for using polymophia.

Michael

**Comment by jklee14** [comment]
Hi Webermich,

    Thanks for getting back. I did resolve the issue. Appreciate you looking into it.

Joe
